[REQ-aliens]
partof = 'REQ-purpose'
text = '''
there shall be a way to say hello to aliens, but that will be harder
'''

[REQ-purpose]
text = '''
This is a project about saying hello to lots of things.
It is split into two sub-requirements:

- [[REQ-world]]: say hello to the world
- [[REQ-aliens]]: say hello to aliens
'''

[REQ-world]
partof = 'REQ-purpose'
text = '''
There shall be way to say hello to the world. All of it.
'''

[SPC-world]
text = '''
The hello-world function shall print hello
'''

[TST-world]
text = '''
We will make a test later.
'''
