[REQ-purpose]
text = '''
We need to be able to say hello to both the world and aliens
'''

[REQ-world]
partof = "REQ-purpose"
text = '''
there shall be way to say hello to the world. All of it.
'''

[REQ-aliens]
partof = "REQ-purpose"
text = '''
there shall be a way to say hello to aliens, but that will be harder
'''

[SPC-world]
text = '''
The hello-world function shall print hello
'''

[TST-world]
text = '''
We will make a test later.
'''
